version: '3.7'
services:
  solver-crud-api-develop:
    env_file: .env
    build:
      context: ""
    restart: always
    container_name: solver-crud-api
    command: sh ./run_server.sh
    environment:
      - POSTGRES_DB=${POSTGRES_DB_DATABASE}
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_SCHEMA=${POSTGRES_DB_SCHEMA}
      - POSTGRES_TABLE=${POSTGRES_DB_TABLE}
      - POSTGRES_PORT=${POSTGRES_DB_PORT}
      - POSTGRES_HOST=${POSTGRES_DB_HOST}
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - solver_develop
  db:
    image: postgres:latest
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB_DATABASE}
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_SCHEMA=${POSTGRES_DB_SCHEMA}
      - POSTGRES_TABLE=${POSTGRES_DB_TABLE}
      - POSTGRES_PORT=${POSTGRES_DB_PORT}
      - POSTGRES_HOST=${POSTGRES_DB_HOST}
    ports:
      - 5433:5432
    networks:
      - solver_develop

networks:
  solver_develop:
    external: true
